image: mcr.microsoft.com/dotnet/sdk:7.0

stages:
  - build
  - test

variables: 
    test: "Infractructure/Servises.UnitTests"

before_script:
    - "dotnet restore"

build:
    stage: build
    script: 
        - "dotnet build"

test:
    stage: test
    script: 
        - "cd $test"
        - "dotnet test"
